# Generated by Django 2.1.5 on 2019-02-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190222_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='items_json',
            field=models.CharField(default='none', max_length=5000),
        ),
    ]
